[package]
name = "fichas_procuracion"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
